import{describe,it,expect}from'vitest';import fs from'node:fs';import path from'node:path';const page=fs.readFileSync(path.resolve('src/pages/AgroHoldingsApproved.tsx'),'utf8'),entity=fs.readFileSync(path.resolve('src/pages/AgroHoldingEntityDetailApproved.tsx'),'utf8'),group=fs.readFileSync(path.resolve('src/pages/AgroHoldingGroupDetailApproved.tsx'),'utf8'),app=fs.readFileSync(path.resolve('src/App.tsx'),'utf8');
describe('Empresas Holdings e Grupos Agro',()=>{
it('usa título correto e três abas',()=>{expect(page).toContain('Empresas, Holdings e Grupos Agro');for(const x of ['Empresas representadas','Candidatos a grupo','Grupos documentais'])expect(page).toContain(x)});
it('remove score e renomeia pessoa selecionada',()=>{expect(page).not.toContain('98/100');expect(page).not.toContain('Força da Relação');expect(page).toContain('Pessoa vinculada selecionada')});
it('mostra taxonomia sem chamar toda empresa de holding',()=>{for(const x of ['EMPRESA_INDIVIDUAL','VINCULO_SOCIETARIO_ISOLADO','HOLDING_DECLARADA','CANDIDATA_A_HOLDING','GRUPO_DOCUMENTAL'])expect(page).toContain(x)});
it('exibe motivo Agro e evidência explicável',()=>{expect(page).toContain('Motivo Agro');expect(page).toContain('Evidência de grupo');expect(page).toContain('NÃO COMPROVADA')});
it('implementa filtros e restauração por URL',()=>{for(const x of ['Município','Tipo de entidade','Motivo Agro','Evidência de grupo','Pessoa com múltiplas empresas','Com propriedade comprovada','Com Empresa 360°','CNAE','Pessoa vinculada','setSp'])expect(page).toContain(x)});
it('pagina cada aba separadamente',()=>{for(const x of ['Anterior','Próxima','Itens por página','total_entities','Página {page}'])expect(page).toContain(x)});
it('possui detalhes de empresa e grupo',()=>{expect(app).toContain('/agro/holdings/empresa/:id');expect(app).toContain('/agro/holdings/grupo/:id');expect(entity).toContain('Nenhum grupo econômico documentalmente comprovado');expect(group).toContain('Critério')});
it('integra pessoa e Empresa 360 apenas com identificador',()=>{expect(page).toContain('/agro/leads/${x.pessoa_selecionada_id}');expect(page).toContain('/empresas/${x.cnpj}');expect(entity).toContain('company_360_url')});
it('declara loading empty error retry e cards mobile',()=>{expect(page).toContain('loading={loading}');for(const x of ['Nenhuma empresa encontrada','Nenhum candidato a grupo encontrado','Nenhum grupo documental identificado','Não foi possível carregar empresas e agrupamentos','onRetry={load}','holding-mobile'])expect(page).toContain(x)});
it('exibe as três notas metodológicas obrigatórias',()=>{expect(page).toContain('não corresponde ao QSA completo');expect(page).toContain('não comprova grupo econômico, controle, beneficiário final');expect(page).toContain('somente quando existe relação persistida e fonte identificável')});
});
