import{describe,it,expect}from'vitest';import fs from'node:fs';import path from'node:path';
const page=fs.readFileSync(path.resolve(__dirname,'../pages/AgroPropriedadesApproved.tsx'),'utf8');const detail=fs.readFileSync(path.resolve(__dirname,'../pages/AgroPropriedadeDetalheApproved.tsx'),'utf8');const api=fs.readFileSync(path.resolve(__dirname,'../pages/agroApiEndpoints.ts'),'utf8');
describe('Catálogo territorial de imóveis rurais',()=>{
 it('possui quatro tabs persistidas na URL',()=>{for(const x of ['Catálogo','Contexto Territorial','Mapa','Metodologia','useSearchParams'])expect(page).toContain(x)});
 it('carrega resumo, lista, contexto e mapa independentemente',()=>{expect((page.match(/Promise\.allSettled/g)||[]).length).toBeGreaterThanOrEqual(4);for(const x of ['summaryError','listError','contextError','mapError'])expect(page).toContain(x)});
 it('possui cards factuais e não transforma null em zero',()=>{for(const x of ['Imóveis rurais registrados','UFs representadas','Municípios representados','Com código IBGE','Com coordenada válida','Área conhecida','Não calculável sob a meta','não é zero'])expect(page).toContain(x);expect(page).toContain("typeof v==='number'")});
 it('possui filtros, paginação e qualidade geográfica',()=>{for(const x of ['Área mínima','Área máxima','Qualidade geográfica','Situação cadastral não disponível','Aplicar filtros','Limpar filtros','[25,50,100]','PROPERTY_COORDINATE','MISSING','INVALID'])expect(page).toContain(x)});
 it('separa contexto municipal de atributo do imóvel',()=>{for(const x of ['Contexto municipal:','Ligação por código IBGE','Os indicadores abaixo descrevem municípios','não são atributos de um imóvel rural individual','IBGE_CODE_EXACT'])expect(page).toContain(x)});
 it('mapa é limitado, dentro do Brasil e responsivo',()=>{for(const x of ['no máximo 1.000 pontos','-33.75','5.27','-73.99','-34.79','prop-mobile','390px'])expect(page).toContain(x)});
 it('não infere produção, produtor, demanda ou fazenda produtiva',()=>{for(const x of ['não comprova atividade produtiva','não equivale a fazenda produtiva','produtor identificado','disponibilidade comercial'])expect(page).toContain(x)});
 it('declara proveniência e contratos novos',()=>{for(const x of ['prospeccao.imovel_rural','prospeccao.v_white_space_pecuaria'])expect(page).toContain(x);for(const x of ['imoveisResumo','imoveisContexto','imoveisMapa'])expect(api).toContain(x)});
 it('detalhe real preserva área, geografia e contexto municipal sem CPF',()=>{for(const x of ['Detalhe do registro SICAR/CAR','Área declarada','Qualidade geográfica','Situação cadastral','O município deste registro está classificado como','descrevem o município, não este imóvel','Nenhum proprietário, produtor'])expect(detail).toContain(x);expect(detail.toLowerCase()).not.toContain('cpf')});
 it('possui estados UNAVAILABLE e NOT_CALCULABLE explícitos',()=>{expect(page).toContain("enrichment?.status==='UNAVAILABLE'");expect(page).toContain('NOT_CALCULABLE');expect(detail).toContain('temporariamente indisponível')});
});
