import{describe,expect,it}from'vitest';import fs from'node:fs';const src=fs.readFileSync('src/pages/AgroTecnicaApproved.tsx','utf8');const api=fs.readFileSync('src/pages/agroApiEndpoints.ts','utf8');
describe('Canal Técnico & Cobertura de Assistência',()=>{
 it('possui cinco abas persistidas na URL',()=>{for(const value of ['Visão Geral','Profissionais','Estabelecimentos','Cobertura Territorial','Metodologia','useSearchParams'])expect(src).toContain(value)});
 it('usa KPI deduplicado e filtro de contato sem soma',()=>{expect(src).toContain("'Registros com contato','com_contato'");expect(src).not.toContain('(stats.com_telefone||0)+(stats.com_email||0)');for(const v of ['PHONE','EMAIL','BOTH','NONE'])expect(src).toContain(v)});
 it('separa naturezas, evidência e não apresenta score',()=>{for(const v of ['Profissional nominal','Estabelecimento veterinário','Inferido pelo CNAE','Identificado nominalmente','Contato institucional'])expect(src).toContain(v);expect(src).not.toContain('score_canal');expect(src).toContain('Nenhum score é apresentado')});
 it('declara CRMV não validado, fontes e limitações',()=>{for(const v of ['CRMV informado','não foi validado oficialmente','Base integrada Canal Técnico','Ausência de registro','não devem ser atribuídos a uma pessoa'])expect(src).toContain(v)});
 it('carrega lista, stats e mapa independentemente',()=>{expect((src.match(/Promise\.allSettled/g)||[]).length).toBeGreaterThanOrEqual(3);expect(src).toContain('listError');expect(src).toContain('statsError');expect(src).toContain('mapError')});
 it('tem mapa municipal dentro dos bounds e mobile específico',()=>{expect(api).toContain("tecnicosMapa: '/agro/tecnicos/mapa'");for(const v of ['MUNICIPAL_NAME_NORMALIZED','-33.75','5.27','-73.99','-34.79','tech-mobile','@media(max-width:700px)'])expect(src).toContain(v)});
});
