import type { EngineeringCompany, EngineeringDataset, EngineeringFilters, EngineeringOpportunity, EngineeringWork } from '../../types/engineering';
import { httpClient } from '../http/client';

type ApiAggregates={works_total:number;investment_total?:number;investment_records_count:number;investment_missing_count:number;investment_unhomologated_count:number;investment_status:'complete'|'partial'|'unavailable';financial_coverage_pct:number;municipality_count:number;company_count:number;missing_municipality_count:number;missing_company_count:number;status_counts:{label:string;value:number}[];phase_counts:{label:string;value:number}[];territories:{municipio:string;uf:string;works_count:number;investment_total?:number;investment_unavailable_count:number;company_count:number;opportunity_count:number;updated_at?:string}[];opportunities:{opportunities_total:number;opportunities_active_total:number;matches_total:number;opportunities_linked:number;opportunities_active:number;matches_linked:number;works_with_opportunity:number;works_without_opportunity:number;active_rule:string};last_updated_at?:string};
type ApiPage<T>={items:T[];total:number;page:number;page_size:number;applied_filters:Record<string,unknown>;aggregates:ApiAggregates;meta:{total:number;source:string;lastUpdatedAt?:string;partialData:boolean}};
type ApiWork={source_id:string;nome:string;descricao?:string;descricao_publica?:string;municipio?:string;uf?:string;latitude?:number;longitude?:number;geoPrecision?:'exact'|'municipality'|'unknown';status?:string;fase?:string;setor?:string;valor_estimado?:number;investment_homologated?:boolean;data_publicacao?:string;data_anuncio?:string;cnpj?:string;empresa?:string;qualityScore:number;partial_data:boolean};
type ApiOpportunity={source_id:string;obra_id:string;cnpj:string;score:number;obra_nome:string;municipio?:string;uf?:string;fornecedor?:string;score_breakdown?:unknown};
type ApiSupplier={source_id:string;razao_social?:string;nome_fantasia?:string;cnae_descricao?:string;municipio?:string;uf?:string;matches_count?:number;source_updated_at?:string;qualityScore:number};

const workStatus=(value?:string):EngineeringWork['status']=>{const v=(value||'').toLowerCase();if(v.includes('conclu'))return 'Concluída';if(v.includes('paralis')||v.includes('suspens'))return 'Paralisada';if(v.includes('andamento')||v.includes('execu'))return 'Em andamento';return 'Prevista'};
const workPhase=(value?:string):EngineeringWork['phase']=>{const v=(value||'').toLowerCase();if(v.includes('licen'))return 'Licenciamento';if(v.includes('mobil'))return 'Mobilização';if(v.includes('execu')||v.includes('obra'))return 'Execução';if(v.includes('entreg')||v.includes('conclu'))return 'Entrega';return 'Projeto'};
const workSector=(value?:string):EngineeringWork['sector']=>{const v=(value||'').toLowerCase();if(v.includes('sanea'))return 'Saneamento';if(v.includes('energ'))return 'Energia';if(v.includes('mobil'))return 'Mobilidade';return 'Rodovias'};
async function getRealDataset(options:EngineeringFilters&{page?:number;pageSize?:number}={}):Promise<EngineeringDataset>{
  const page=options.page||1;const pageSize=options.pageSize||100;
  const [worksResult,opportunitiesResult,suppliersResult]=await Promise.allSettled([
    httpClient.get<ApiPage<ApiWork>>('/engenharia/obras',{timeout:30000,params:{page,page_size:pageSize,search:options.search||undefined,status:options.status,phase:options.phase,sector:options.sector,municipality:options.municipality,uf:options.uf,company:options.company,investment_min:options.investmentMin,investment_max:options.investmentMax,period_start:options.periodStart,period_end:options.periodEnd,has_supplier:options.hasSupplier,has_decision_maker:options.hasDecisionMaker,has_opportunity:options.hasOpportunity,capex_homologado:options.capexHomologado,sort:options.sort||'investment_desc'}}),
    httpClient.get<ApiPage<ApiOpportunity>>('/engenharia/oportunidades',{timeout:30000,params:{page:1,page_size:100,min_score:70}}),
    httpClient.get<ApiPage<ApiSupplier>>('/engenharia/fornecedores',{timeout:30000,params:{page:1,page_size:100,active:true}}),
  ]);
  const emptyAggregates:ApiAggregates={works_total:0,investment_records_count:0,investment_missing_count:0,investment_unhomologated_count:0,investment_status:'unavailable',financial_coverage_pct:0,municipality_count:0,company_count:0,missing_municipality_count:0,missing_company_count:0,status_counts:[],phase_counts:[],territories:[],opportunities:{opportunities_total:0,opportunities_active_total:0,matches_total:0,opportunities_linked:0,opportunities_active:0,matches_linked:0,works_with_opportunity:0,works_without_opportunity:0,active_rule:'score >= 70'}};
  const worksData=worksResult.status==='fulfilled'?worksResult.value.data:{items:[],total:0,page,page_size:pageSize,applied_filters:{},aggregates:emptyAggregates,meta:{total:0,source:'API Onda 1',partialData:false}};
  const oppsData=opportunitiesResult.status==='fulfilled'?opportunitiesResult.value.data:{items:[],meta:{total:0,source:'',partialData:false}};
  const suppliersData=suppliersResult.status==='fulfilled'?suppliersResult.value.data:{items:[],meta:{total:0,source:'',partialData:false}};
  const works:EngineeringWork[]=worksData.items.map((w,index)=>({
    id:w.source_id,name:w.nome,description:w.descricao_publica||w.descricao||'Descrição parcial na fonte de origem.',
    municipality:w.municipio||'Município não informado',state:w.uf||'—',coordinates:[Number(w.latitude)||-15.78,Number(w.longitude)||-47.93],geoPrecision:w.geoPrecision||'unknown',
    status:workStatus(w.status),phase:workPhase(w.fase),sector:workSector(w.setor),investment:w.valor_estimado!=null&&w.investment_homologated?Number(w.valor_estimado):undefined,investmentHomologated:!!w.investment_homologated,
    progress:workPhase(w.fase)==='Entrega'?100:workPhase(w.fase)==='Execução'?55:workPhase(w.fase)==='Mobilização'?30:15,
    startDate:w.data_publicacao?new Date(w.data_publicacao).toLocaleDateString('pt-BR'):'Não informado',
    deadline:w.data_anuncio?new Date(w.data_anuncio).toLocaleDateString('pt-BR'):'Prazo não informado',
    companyIds:w.cnpj?[w.cnpj]:[],priority:index<20?'Alta':index<60?'Média':'Baixa',
    indicators:[{label:'Qualidade da fonte',value:`${w.qualityScore}%`},{label:'Precisão geográfica',value:w.geoPrecision==='municipality'?'Localização aproximada · centroide municipal':w.geoPrecision==='exact'?'Localização exata':'Localização ausente'}],
    events:[{date:w.data_publicacao?new Date(w.data_publicacao).toLocaleDateString('pt-BR'):'Sem data',title:'Registro capturado',detail:'Evento derivado da atualização da fonte real.'}],
  }));
  const companyMap=new Map<string,EngineeringCompany>();
  for(const s of suppliersData.items){companyMap.set(s.source_id,{id:s.source_id,name:s.razao_social||s.nome_fantasia||'Razão social não informada',tradeName:s.nome_fantasia||s.razao_social||'Nome não informado',cnpj:s.source_id,segment:s.cnae_descricao||'Segmento não informado',municipality:s.municipio||'Município não informado',state:s.uf||'—',founded:'Não informado',employees:0,revenue:0,score:s.qualityScore||0,workIds:[],opportunityIds:[],territories:s.uf?[s.uf]:[],links:[],history:[{date:s.source_updated_at?new Date(s.source_updated_at).toLocaleDateString('pt-BR'):'Sem data',title:'Cadastro legado atualizado',detail:'Fonte wins_agro.engenharia.fornecedores'}]})}
  for(const w of worksData.items){if(!w.cnpj)continue;const current=companyMap.get(w.cnpj);if(current){if(!current.workIds.includes(w.source_id))current.workIds.push(w.source_id);continue}companyMap.set(w.cnpj,{id:w.cnpj,name:w.empresa||`Empresa ${w.cnpj}`,tradeName:w.empresa||'Empresa',cnpj:w.cnpj,segment:w.setor||'Engenharia',municipality:w.municipio||'Não informado',state:w.uf||'—',founded:'Não informado',employees:0,revenue:0,score:w.qualityScore||50,workIds:[w.source_id],opportunityIds:[],territories:w.uf?[w.uf]:[],links:[{type:'Obra',name:w.nome}],history:[{date:w.data_publicacao?new Date(w.data_publicacao).toLocaleDateString('pt-BR'):'Sem data',title:'Vínculo identificado',detail:'Fonte real de Engenharia'}]})}
  const opportunities:EngineeringOpportunity[]=oppsData.items.filter(o=>works.some(w=>w.id===o.obra_id)).map(o=>({id:o.source_id,title:`Fornecedor relacionado a ${o.obra_nome}`,sector:works.find(w=>w.id===o.obra_id)?.sector||'Rodovias',municipality:o.municipio||'Não informado',estimatedValue:undefined as unknown as number,stage:Number(o.score)>=85?'Qualificação':'Identificada',companyId:o.cnpj,workId:o.obra_id,score:Math.round(Number(o.score)||0),justification:`Matching real baseado nos critérios registrados na fonte; score ${o.score}.`}));
  for(const o of opportunities){const c=companyMap.get(o.companyId);if(c&&!c.opportunityIds.includes(o.id))c.opportunityIds.push(o.id)}
  const errors:string[]=[];
  if(worksResult.status==='rejected')errors.push(`Obras: ${worksResult.reason?.message||'Falha na requisição'}`);
  if(opportunitiesResult.status==='rejected')errors.push(`Oportunidades: ${opportunitiesResult.reason?.message||'Falha na requisição'}`);
  if(suppliersResult.status==='rejected')errors.push(`Fornecedores: ${suppliersResult.reason?.message||'Falha na requisição'}`);
  const a=worksData.aggregates;
  return {works,companies:[...companyMap.values()],opportunities,meta:{source:worksData.meta.source||'API Onda 1',lastUpdatedAt:worksData.meta.lastUpdatedAt,partialData:worksData.meta.partialData,totalWorks:worksData.total,page:worksData.page,pageSize:worksData.page_size,appliedFilters:options,aggregates:{worksTotal:a.works_total,investmentTotal:a.investment_total!=null?Number(a.investment_total):undefined,investmentRecordsCount:a.investment_records_count,investmentMissingCount:a.investment_missing_count,investmentUnhomologatedCount:a.investment_unhomologated_count,investmentStatus:a.investment_status,financialCoveragePct:Number(a.financial_coverage_pct||0),municipalityCount:a.municipality_count,companyCount:a.company_count,missingMunicipalityCount:a.missing_municipality_count,missingCompanyCount:a.missing_company_count,statusCounts:a.status_counts||[],phaseCounts:a.phase_counts||[],territories:(a.territories||[]).map(t=>({municipality:t.municipio,uf:t.uf,worksCount:Number(t.works_count),investmentTotal:t.investment_total!=null?Number(t.investment_total):undefined,investmentUnavailableCount:Number(t.investment_unavailable_count),companyCount:Number(t.company_count),opportunityCount:Number(t.opportunity_count),updatedAt:t.updated_at})),opportunities:{opportunitiesTotal:Number(a.opportunities?.opportunities_total||0),opportunitiesActiveTotal:Number(a.opportunities?.opportunities_active_total||0),matchesTotal:Number(a.opportunities?.matches_total||0),opportunitiesLinked:Number(a.opportunities?.opportunities_linked||0),opportunitiesActive:Number(a.opportunities?.opportunities_active||0),matchesLinked:Number(a.opportunities?.matches_linked||0),worksWithOpportunity:Number(a.opportunities?.works_with_opportunity||0),worksWithoutOpportunity:Number(a.opportunities?.works_without_opportunity||0),activeRule:a.opportunities?.active_rule||'score >= 70'},lastUpdatedAt:a.last_updated_at},realData:true,error:errors.join('; ')||undefined}};
}

export const engineeringService = {
  async load(options:EngineeringFilters&{page?:number;pageSize?:number}={}):Promise<EngineeringDataset>{return getRealDataset(options)},
  async getWorks():Promise<EngineeringWork[]>{return (await getRealDataset()).works},
  async getWork(id:string):Promise<EngineeringWork|undefined>{const r=await httpClient.get(`/engenharia/obras/${id}`);const d=r.data;return {id:d.sourceId,name:d.name,description:d.description||'Descrição não informada na fonte.',municipality:d.municipality||'Município não informado',state:d.state||'—',coordinates:[Number(d.latitude)||0,Number(d.longitude)||0],geoPrecision:d.geoPrecision||'unknown',status:workStatus(d.status),phase:workPhase(d.phase),sector:workSector(d.sector),investment:d.value!=null?Number(d.value):undefined,progress:workPhase(d.phase)==='Entrega'?100:workPhase(d.phase)==='Execução'?55:workPhase(d.phase)==='Mobilização'?30:15,startDate:d.publishedAt?new Date(d.publishedAt).toLocaleDateString('pt-BR'):'Não informado',deadline:d.deadline?new Date(d.deadline).toLocaleDateString('pt-BR'):'Prazo não informado',companyIds:d.company?.cnpj?[d.company.cnpj]:[],priority:'Alta',indicators:[{label:'Fonte',value:d.source||d.provenance?.sourceTable||'não informada'},{label:'Atualização',value:d.lastUpdatedAt?new Date(d.lastUpdatedAt).toLocaleDateString('pt-BR'):'não informada'}],events:[]}},
  async getCompanies():Promise<EngineeringCompany[]>{return (await getRealDataset()).companies},
  async getCompany(id:string):Promise<EngineeringCompany|undefined>{const r=await httpClient.get(`/empresas/${id}`);const d=r.data;return {id:d.cnpj,name:d.legalName||'Razão social não informada',tradeName:d.tradeName||d.legalName||'Nome não informado',cnpj:d.cnpj,segment:d.supplierProfile?.cnae_descricao||'Engenharia',municipality:d.address?.municipality||'Município não informado',state:d.address?.state||'—',founded:'Não informado',employees:0,revenue:Number(d.capital)||0,score:Number(d.qualityScore)||0,workIds:(d.works||[]).map((w:{id:string})=>w.id),opportunityIds:(d.opportunities||[]).map((o:{obra_id:string})=>`${o.obra_id}-${d.cnpj}`),territories:d.address?.state?[d.address.state]:[],links:(d.works||[]).slice(0,8).map((w:{nome:string})=>({type:'Obra',name:w.nome})),history:[{date:d.lastUpdatedAt?new Date(d.lastUpdatedAt).toLocaleDateString('pt-BR'):'Sem data',title:'Cadastro consolidado',detail:`Fonte ${d.provenance?.sourceSchema}.${d.provenance?.sourceTable}`} ]}},
  async getOpportunities():Promise<EngineeringOpportunity[]>{return (await getRealDataset()).opportunities},
  async getMap(params:Record<string,unknown>):Promise<{clusters:Array<{layer:'works'|'companies'|'suppliers'|'opportunities';latitude:number;longitude:number;quantity:number;municipality_count:number;municipality:string;uf:string;sample_id:string;updated_at?:string;geoPrecision:string;source:string;detailUrl:string;locationLabel:string;approximateLocation:boolean}>;totals:Record<string,number>;total:number;strategy:string;sampled:boolean;truncated:boolean;zoom:number}> {return (await httpClient.get('/engenharia/mapa',{params,timeout:30000})).data},
  async getConnections(params:Record<string,unknown>):Promise<{kpis:{multiverticalCompanies:number;multiverticalSuppliers:number;fourVerticalMunicipalities:number;transversalOpportunities:number;confirmedRelations:number;potentialRelations:number};relations:Array<{cnpj:string;name:string;vertical:string;classification:'CONFIRMADO'|'PROVÁVEL'|'POTENCIAL';rule:string;confidence:number;source:string;updatedAt?:string;worksCount:number;opportunitiesCount:number;company360Url:string;worksUrl:string;occurrencesUrl:string;opportunitiesUrl:string}>;municipalPotential:Array<{municipality:string;uf:string;classification:string;rule:string;confidence:number}>;source:string}> {return (await httpClient.get('/engenharia/conexoes',{params,timeout:30000})).data},
};
