export const AGRO_API = {
  kpis: '/agro/kpis',
  distribuicao: '/agro/distribuicao',
  mapa: '/agro/mapa',
  oportunidades: '/agro/oportunidades',
  oportunidadesStatus: '/agro/oportunidades/status',
  oportunidadesFunil: '/agro/oportunidades/funil',
  oportunidadesRegras: '/agro/oportunidades/regras',
  oportunidadesEstagios: '/agro/oportunidades/estagios',
  relacoes: '/agro/relacoes',
  oportunidadesCalculadas: '/agro/oportunidades/calculadas',
  logisticaCorrelacao: '/agro/logistica/correlacao',
  logisticaResumo: '/agro/logistica/resumo',
  logisticaMunicipios: '/agro/logistica/municipios',
  logisticaMapa: '/agro/logistica/mapa',
  geneticaSimulador: '/agro/genetica/simulador',
  decisores: '/agro/decisores',
  people: '/agro/pessoas-vinculos',
  peopleStats: '/agro/pessoas-vinculos/stats',
  person: (id: string) => `/agro/pessoas-vinculos/${encodeURIComponent(id)}`,
  holdings: '/agro/holdings',
  holdingsStats: '/agro/holdings/stats',
  holdingEntity: (id: string) => `/agro/holdings/entities/${encodeURIComponent(id)}`,
  holdingGroup: (id: string) => `/agro/holdings/groups/${encodeURIComponent(id)}`,
  imoveis: '/agro/imoveis',
  imovel: (id: string) => `/agro/imoveis/${encodeURIComponent(id)}`,
  tecnicos: '/agro/tecnicos',
  tecnicosStats: '/agro/tecnicos/stats',
  tecnico: (id: string) => `/agro/tecnicos/${encodeURIComponent(id)}`,
  desertoVeterinario: '/agro/deserto-veterinario',
  desertoVeterinarioStats: '/agro/deserto-veterinario/stats',
} as const;
