import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {Filter,Search,SlidersHorizontal} from 'lucide-react';
import AgroPageShell from '../components/AgroPageShell';
import {BrazilUfSelect} from '../components/territorial/BrazilUfSelect';
import {httpClient} from '../services/http/client';import {AGRO_API} from './agroApiEndpoints';

type Filters={q:string;uf:string;municipio:string;area_min:string;area_max:string;completude_min:string;cobertura_veterinaria:string;com_titular:string;com_cnpj:string;com_bioma:string;com_uso_solo:string;fonte:string;somente_ficha:string};
const defaults:Filters={q:'',uf:'',municipio:'',area_min:'',area_max:'',completude_min:'',cobertura_veterinaria:'',com_titular:'',com_cnpj:'',com_bioma:'',com_uso_solo:'',fonte:'',somente_ficha:''};
const num=(v:any)=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('pt-BR'):'Não disponível';
const coverage:Record<string,string>={DESERTO_VET:'Deserto Vet',BAIXA_COBERTURA:'Baixa Cobertura',NORMAL:'Normal',INDISPONIVEL:'Indisponível'};
const complete=(n:number)=>n>=80?'Alta completude':n>=50?'Parcial':'Territorial básico';
function fromUrl(p:URLSearchParams):Filters{const f={...defaults};Object.keys(f).forEach(k=>{(f as any)[k]=p.get(k)||''});return f}

export default function AgroPropriedadesApproved(){
 const nav=useNavigate(),[sp,setSp]=useSearchParams();const initial=useMemo(()=>fromUrl(sp),[]);
 const[form,setForm]=useState<Filters>(initial),[filters,setFilters]=useState<Filters>(initial),[items,setItems]=useState<any[]>([]),[total,setTotal]=useState(0),[pages,setPages]=useState(0),[status,setStatus]=useState('ok'),[limitations,setLimitations]=useState<string[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[more,setMore]=useState(false),[page,setPage]=useState(Number(sp.get('page'))||1),[pageSize,setPageSize]=useState(Number(sp.get('page_size'))||25),[sort,setSort]=useState(sp.get('sort')||'relevancia'),[order,setOrder]=useState(sp.get('order')||'desc');const abort=useRef<AbortController|null>(null);
 const load=useCallback(async()=>{abort.current?.abort();const c=new AbortController();abort.current=c;setLoading(true);setError(null);try{const params:any={page,page_size:pageSize,sort,order};Object.entries(filters).forEach(([k,v])=>{if(v&&k!=='fonte'&&k!=='somente_ficha')params[k]=v});const r=await httpClient.get(AGRO_API.imoveis,{params,signal:c.signal});setItems((r.data.items||[]).filter((x:any)=>filters.somente_ficha?x.detail_available:true));setTotal(r.data.total||0);setPages(r.data.total_pages||0);setStatus(r.data.status||'ok');setLimitations(r.data.limitations||[])}catch(e:any){if(e?.name==='CanceledError'||e?.name==='AbortError')return;setError(e?.message||'Não foi possível carregar o catálogo de propriedades.');setItems([])}finally{if(!c.signal.aborted)setLoading(false)}},[filters,page,pageSize,sort,order]);
 useEffect(()=>{load();return()=>abort.current?.abort()},[load]);
 useEffect(()=>{const t=setTimeout(()=>{if(form.q!==filters.q){setFilters(x=>({...x,q:form.q}));setPage(1)}},450);return()=>clearTimeout(t)},[form.q,filters.q]);
 useEffect(()=>{const p:any={};Object.entries(filters).forEach(([k,v])=>{if(v)p[k]=v});if(page>1)p.page=String(page);if(pageSize!==25)p.page_size=String(pageSize);if(sort!=='relevancia')p.sort=sort;if(order!=='desc')p.order=order;setSp(p,{replace:true})},[filters,page,pageSize,sort,order,setSp]);
 const apply=()=>{setFilters(form);setPage(1)},clear=()=>{setForm(defaults);setFilters(defaults);setPage(1);setSort('relevancia');setOrder('desc')};const active=Object.values(filters).filter(Boolean).length;
 const summary=useMemo(()=>({shown:items.length,owners:items.filter(x=>x.titular_nome).length,cnpj:items.filter(x=>x.cnpj_vinculado).length,desert:items.filter(x=>x.cobertura_veterinaria==='DESERTO_VET').length,low:items.filter(x=>x.cobertura_veterinaria==='BAIXA_COBERTURA').length,area:items.reduce((s,x)=>s+(typeof x.area_ha==='number'?x.area_ha:0),0),avg:items.length?Math.round(items.reduce((s,x)=>s+(x.completude_score||0),0)/items.length):0}),[items]);
 const sortBy=(s:string)=>{setPage(1);if(sort===s)setOrder(o=>o==='asc'?'desc':'asc');else{setSort(s);setOrder(s==='municipio'||s==='uf'||s==='codigo_car'?'asc':'desc')}};const start=total?(page-1)*pageSize+1:0,end=Math.min(page*pageSize,total);
 const filter=(k:keyof Filters,v:string)=>setForm(x=>({...x,[k]:v}));
 const owner=(i:any)=><><strong>{i.titular_nome||'Titular não disponibilizado na fonte'}</strong><small>{i.cnpj_vinculado?`CNPJ ${i.cnpj_vinculado} — ${i.cnpj_evidencia}`:'Sem vínculo empresarial comprovado'}</small></>;
 const action=(i:any)=><button disabled={!i.detail_available} title={i.detail_available?'Abrir Ficha 360°':'Ficha indisponível para este cadastro'} onClick={()=>i.detail_available&&nav(`/agro/propriedades/${encodeURIComponent(i.detail_id)}`)}>Ficha 360°</button>;
 return <AgroPageShell title="Catálogo de Propriedades Rurais" subtitle="Cadastros declaratórios do SICAR/CAR" loading={loading} error={error} onRetry={load} empty={!loading&&!error&&!items.length} emptyMessage="Nenhuma propriedade encontrada com os filtros atuais.">
  <section className="agro-property-filters"><div className="property-filter-main"><label><Search size={15}/><input aria-label="Busca" placeholder="Código CAR, cadastro, titular ou município" value={form.q} onChange={e=>filter('q',e.target.value)}/></label><BrazilUfSelect value={form.uf} onChange={v=>filter('uf',v)} showAllLabel="Todas as UFs"/><input aria-label="Município" placeholder="Município" value={form.municipio} onChange={e=>filter('municipio',e.target.value)}/><input aria-label="Área mínima" type="number" placeholder="Área mínima" value={form.area_min} onChange={e=>filter('area_min',e.target.value)}/><input aria-label="Área máxima" type="number" placeholder="Área máxima" value={form.area_max} onChange={e=>filter('area_max',e.target.value)}/><input aria-label="Completude mínima" type="number" min="0" max="100" placeholder="Completude mín." value={form.completude_min} onChange={e=>filter('completude_min',e.target.value)}/><select aria-label="Cobertura veterinária" value={form.cobertura_veterinaria} onChange={e=>filter('cobertura_veterinaria',e.target.value)}><option value="">Toda cobertura</option>{Object.entries(coverage).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select aria-label="Com titular" value={form.com_titular} onChange={e=>filter('com_titular',e.target.value)}><option value="">Titular: todos</option><option value="true">Com titular</option><option value="false">Sem titular</option></select><select aria-label="Com CNPJ" value={form.com_cnpj} onChange={e=>filter('com_cnpj',e.target.value)}><option value="">CNPJ: todos</option><option value="true">Com CNPJ</option><option value="false">Sem CNPJ</option></select></div><div className="property-filter-actions"><button onClick={()=>setMore(x=>!x)}><SlidersHorizontal size={14}/>Mais filtros</button><button onClick={clear}>Limpar</button><button className="primary" onClick={apply}><Filter size={14}/>Aplicar filtros</button><span>{active} filtros ativos</span></div>{more&&<div className="property-more-filters"><select aria-label="Com bioma" value={form.com_bioma} onChange={e=>filter('com_bioma',e.target.value)}><option value="">Bioma: todos</option><option value="true">Com bioma</option><option value="false">Sem bioma</option></select><select aria-label="Com uso do solo" value={form.com_uso_solo} onChange={e=>filter('com_uso_solo',e.target.value)}><option value="">Uso: todos</option><option value="true">Com uso do solo</option><option value="false">Sem uso do solo</option></select><select aria-label="Fonte" value={form.fonte} onChange={e=>filter('fonte',e.target.value)}><option value="">Todas as fontes</option><option value="SICAR">SICAR/CAR</option></select><label><input type="checkbox" checked={form.somente_ficha==='true'} onChange={e=>filter('somente_ficha',e.target.checked?'true':'')}/>Somente ficha disponível</label></div>}</section>
  {status==='partial'&&<div className="property-partial">Alguns enriquecimentos não estão disponíveis para este recorte.</div>}
  <section className="property-page-summary"><h3>Resumo da página atual</h3>{[['Registros exibidos',summary.shown],['Com titular',summary.owners],['Com CNPJ',summary.cnpj],['Deserto Vet',summary.desert],['Baixa Cobertura',summary.low],['Área total exibida',`${num(summary.area)} ha`],['Completude média',`${summary.avg}%`]].map(([l,v])=><div key={l}><small>{l}</small><strong>{v}</strong></div>)}</section>
  <div className="property-table-wrap"><table className="property-table"><thead><tr><th onClick={()=>sortBy('codigo_car')}>CAR / Cadastro</th><th>Titular / vínculo empresarial</th><th onClick={()=>sortBy('municipio')}>Município / UF</th><th onClick={()=>sortBy('area')}>Área</th><th onClick={()=>sortBy('completude')}>Completude</th><th>Cobertura veterinária</th><th>Bioma / Uso</th><th>Ação</th></tr></thead><tbody>{items.map(i=><tr key={i.detail_id}><td><strong>{i.codigo_car_exibicao||'Código CAR não disponível'}</strong><small>Cadastro declaratório</small></td><td>{owner(i)}</td><td>{i.municipio||'Município não disponível'} / {i.uf||'UF não disponível'}</td><td>{typeof i.area_ha==='number'?`${num(i.area_ha)} ha`:'Área não disponível'}</td><td><span className={`complete c${Math.floor((i.completude_score||0)/10)}`}>{i.completude_score}% · {complete(i.completude_score)}</span></td><td><span className={`coverage ${i.cobertura_veterinaria}`}>{coverage[i.cobertura_veterinaria]||'Indisponível'}</span><small>Classificação municipal</small></td><td><strong>{i.bioma||'Bioma não disponível'}</strong><small>{i.bioma?i.bioma_origem:'Uso do solo não disponível'}{i.uso_solo?' · Uso declarado no CAR':''}</small></td><td>{action(i)}</td></tr>)}</tbody></table></div>
  <div className="property-mobile-list">{items.map(i=><article key={i.detail_id}><strong>{i.codigo_car_exibicao||'Código CAR não disponível'}</strong><span>{i.municipio||'Município não disponível'} / {i.uf||'UF não disponível'}</span><span>{typeof i.area_ha==='number'?`${num(i.area_ha)} ha`:'Área não disponível'}</span><span>{i.completude_score}% · {complete(i.completude_score)}</span><span>{coverage[i.cobertura_veterinaria]||'Indisponível'}</span>{action(i)}</article>)}</div>
  <div className="property-pagination"><span>Exibindo {num(start)}–{num(end)} de {num(total)} registros</span><div><button disabled={page<=1} onClick={()=>setPage(1)}>Primeira</button><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</button><b>Página {page} de {num(pages)}</b><button disabled={page>=pages||page>=1000} onClick={()=>setPage(p=>p+1)}>Próxima</button><select aria-label="Registros por página" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}>{[25,50,100].map(n=><option key={n}>{n}</option>)}</select></div></div>
  {limitations.length>0&&<small>{limitations.join(' ')}</small>}<p className="property-legal-note">Os registros são cadastros declaratórios do SICAR/CAR e não comprovam titularidade, domínio ou limites fundiários.</p>
 </AgroPageShell>
}
