export const AGRO_API = {
  kpis: '/agro/kpis',
  distribuicao: '/agro/distribuicao',
  mapa: '/agro/mapa',
  oportunidades: '/agro/oportunidades',
  oportunidadesStatus: '/agro/oportunidades/status',
  oportunidadesFunil: '/agro/oportunidades/funil',
  oportunidadesRegras: '/agro/oportunidades/regras',
  oportunidadesEstagios: '/agro/oportunidades/estagios',
  relacoes: '/agro/relacoes',
  oportunidadesCalculadas: '/agro/oportunidades/calculadas',
  logisticaCorrelacao: '/agro/logistica/correlacao',
  logisticaResumo: '/agro/logistica/resumo',
  logisticaMunicipios: '/agro/logistica/municipios',
  logisticaMapa: '/agro/logistica/mapa',
  geneticaResumo: '/agro/genetica/resumo',
  geneticaReprodutores: '/agro/genetica/reprodutores',
  geneticaReprodutor: (id: string) => `/agro/genetica/reprodutores/${encodeURIComponent(id)}`,
  geneticaCaracteristicas: '/agro/genetica/caracteristicas',
  geneticaPedigree: (id: string) => `/agro/genetica/reprodutores/${encodeURIComponent(id)}/pedigree`,
  geneticaAcasalamentoProntidao: '/agro/genetica/acasalamento/prontidao',
  geneticaAcasalamentoCandidatos: '/agro/genetica/acasalamento/candidatos',
  geneticaSimulador: '/agro/genetica/simulador',
  geneticaMatrizes: '/agro/genetica/matrizes',
  geneticaMetodologia: '/agro/genetica/metodologia',
  decisores: '/agro/decisores',
  people: '/agro/pessoas-vinculos',
  peopleStats: '/agro/pessoas-vinculos/stats',
  person: (id: string) => `/agro/pessoas-vinculos/${encodeURIComponent(id)}`,
  holdings: '/agro/holdings',
  holdingsStats: '/agro/holdings/stats',
  holdingEntity: (id: string) => `/agro/holdings/entities/${encodeURIComponent(id)}`,
  holdingGroup: (id: string) => `/agro/holdings/groups/${encodeURIComponent(id)}`,
  imoveis: '/agro/imoveis',
  imoveisResumo: '/agro/imoveis/resumo',
  imoveisContexto: '/agro/imoveis/contexto-territorial',
  imoveisMapa: '/agro/imoveis/mapa',
  imovel: (id: string) => `/agro/imoveis/${encodeURIComponent(id)}`,
  tecnicos: '/agro/tecnicos',
  tecnicosStats: '/agro/tecnicos/stats',
  tecnicosMapa: '/agro/tecnicos/mapa',
  tecnico: (id: string) => `/agro/tecnicos/${encodeURIComponent(id)}`,
  desertoVeterinario: '/agro/deserto-veterinario',
  desertoVeterinarioStats: '/agro/deserto-veterinario/stats',
  desertoVeterinarioResumo: '/agro/deserto-veterinario/resumo',
  desertoVeterinarioMunicipios: '/agro/deserto-veterinario/municipios',
  desertoVeterinarioMapa: '/agro/deserto-veterinario/mapa',
  desertoVeterinarioMetodologia: '/agro/deserto-veterinario/metodologia',
  desertoVeterinarioDetalhe: (codigoIbge: string) =>
    `/agro/deserto-veterinario/${encodeURIComponent(codigoIbge)}`,
} as const;
