import React,{useCallback,useEffect,useState}from'react';
import{Link,useNavigate,useSearchParams}from'react-router-dom';
import{CircleMarker,MapContainer,TileLayer,Tooltip}from'react-leaflet';
import AgroPageShell from'../components/AgroPageShell';
import{BrazilUfSelect}from'../components/territorial/BrazilUfSelect';
import{httpClient}from'../services/http/client';import{AGRO_API}from'./agroApiEndpoints';import'leaflet/dist/leaflet.css';

const tabs=[['catalogo','Catálogo'],['territorio','Contexto Territorial'],['mapa','Mapa'],['metodologia','Metodologia']]as const;
const blank={q:'',uf:'',municipio:'',area_min:'',area_max:'',geographic_quality:'',cobertura_veterinaria:''};
const geo:Record<string,string>={PROPERTY_COORDINATE:'Coordenada própria do registro',MUNICIPAL_REFERENCE:'Referência municipal',MISSING:'Coordenada ausente',INVALID:'Coordenada inválida'};
const coverage:Record<string,string>={DESERTO_VET:'Deserto Veterinário',BAIXA_COBERTURA:'Baixa presença conhecida',NORMAL:'Presença técnica conhecida',INDISPONIVEL:'Contexto indisponível'};
const fmt=(v:any)=>typeof v==='number'?v.toLocaleString('pt-BR'):'Não calculável';
const box:React.CSSProperties={background:'var(--bg-surface)',border:'1px solid var(--border-default)',borderRadius:10,padding:14};

export default function AgroPropriedadesApproved(){
 const nav=useNavigate(),[sp,setSp]=useSearchParams();const tab=tabs.some(([v])=>v===sp.get('tab'))?(sp.get('tab')as string):'catalogo';
 const[summary,setSummary]=useState<any>(null),[items,setItems]=useState<any[]>([]),[context,setContext]=useState<any[]>([]),[points,setPoints]=useState<any[]>([]);
 const[summaryError,setSummaryError]=useState<string|null>(null),[listError,setListError]=useState<string|null>(null),[contextError,setContextError]=useState<string|null>(null),[mapError,setMapError]=useState<string|null>(null);
 const[summaryLoading,setSummaryLoading]=useState(false),[listLoading,setListLoading]=useState(false),[contextLoading,setContextLoading]=useState(false),[mapLoading,setMapLoading]=useState(false);
 const[page,setPage]=useState(Number(sp.get('page'))||1),[pageSize,setPageSize]=useState(Number(sp.get('page_size'))||25),[pages,setPages]=useState(0),[total,setTotal]=useState(0),[enrichment,setEnrichment]=useState<any>(null);
 const initial={...blank,...Object.fromEntries(Object.keys(blank).map(k=>[k,sp.get(k)||'']))};const[form,setForm]=useState<any>(initial),[filters,setFilters]=useState<any>(initial);
 const setTab=(value:string)=>{const q=new URLSearchParams(sp);q.set('tab',value);q.delete('page');setSp(q);setPage(1)};
 const loadSummary=useCallback(async()=>{setSummaryLoading(true);setSummaryError(null);const[r]=await Promise.allSettled([httpClient.get(AGRO_API.imoveisResumo)]);if(r.status==='fulfilled')setSummary(r.value.data);else setSummaryError('O resumo está temporariamente indisponível; nenhum indicador foi convertido em zero.');setSummaryLoading(false)},[]);
 const loadList=useCallback(async()=>{if(tab!=='catalogo')return;setListLoading(true);setListError(null);const params:any={page,page_size:pageSize};Object.entries(filters).forEach(([k,v])=>{if(v!=='')params[k]=v});const[r]=await Promise.allSettled([httpClient.get(AGRO_API.imoveis,{params})]);if(r.status==='fulfilled'){setItems(r.value.data.items||[]);setTotal(r.value.data.total);setPages(r.value.data.total_pages);setEnrichment(r.value.data.enrichment)}else setListError('Não foi possível carregar os registros SICAR/CAR. O erro não foi convertido em lista vazia.');setListLoading(false)},[filters,page,pageSize,tab]);
 const loadContext=useCallback(async()=>{if(tab!=='territorio')return;setContextLoading(true);setContextError(null);const[r]=await Promise.allSettled([httpClient.get(AGRO_API.imoveisContexto,{params:{uf:filters.uf||undefined,municipio:filters.municipio||undefined,limit:100}})]);if(r.status==='fulfilled')setContext(r.value.data.items||[]);else setContextError('Contexto territorial temporariamente indisponível. Os dados cadastrais permanecem válidos.');setContextLoading(false)},[filters.uf,filters.municipio,tab]);
 const loadMap=useCallback(async()=>{if(tab!=='mapa')return;setMapLoading(true);setMapError(null);const[r]=await Promise.allSettled([httpClient.get(AGRO_API.imoveisMapa,{params:{uf:filters.uf||undefined,municipio:filters.municipio||undefined,limit:1000}})]);if(r.status==='fulfilled')setPoints(r.value.data.items||[]);else setMapError('O recorte cartográfico está temporariamente indisponível.');setMapLoading(false)},[filters.uf,filters.municipio,tab]);
 useEffect(()=>{loadSummary()},[loadSummary]);useEffect(()=>{loadList()},[loadList]);useEffect(()=>{loadContext()},[loadContext]);useEffect(()=>{loadMap()},[loadMap]);
 const apply=()=>{setFilters({...form});setPage(1);const q=new URLSearchParams();q.set('tab',tab);q.set('page_size',String(pageSize));Object.entries(form).forEach(([k,v])=>{if(v)q.set(k,String(v))});setSp(q)};const clear=()=>{setForm({...blank});setFilters({...blank});setPage(1);setSp({tab})};const active=Object.values(form).filter(Boolean).length;
 const cards=[['Imóveis rurais registrados','total'],['UFs representadas','ufs'],['Municípios representados','municipios'],['Com código IBGE','com_codigo_ibge'],['Com coordenada válida','com_coordenada_valida'],['Área conhecida','area_conhecida']];
 return <AgroPageShell title="Catálogo Territorial de Imóveis Rurais" subtitle="Registros SICAR/CAR com localização, proveniência e contexto municipal explicitamente separados.">
  <style>{`.prop-tabs{display:flex;gap:8px;overflow:auto}.prop-tabs button{white-space:nowrap}.prop-tabs .active{background:#166534;color:white}.prop-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px;margin-top:14px}.prop-filters{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:9px}.prop-actions{display:flex;gap:9px;align-items:center;flex-wrap:wrap;margin-top:10px}.prop-table{overflow:auto}.prop-table table{min-width:900px;width:100%}.prop-mobile{display:none}.prop-warning{padding:10px;border-left:3px solid #f59e0b;background:rgba(245,158,11,.08);margin:10px 0}.prop-section{margin-top:14px}.prop-badge{display:inline-block;border-radius:999px;padding:3px 8px;background:rgba(34,197,94,.12)}@media(max-width:700px){.prop-filters{grid-template-columns:1fr}.prop-table{display:none}.prop-mobile{display:grid;gap:10px}.prop-kpis{grid-template-columns:1fr 1fr}.prop-map{height:390px!important}}`}</style>
  <nav className="prop-tabs" aria-label="Seções de Propriedades">{tabs.map(([v,l])=><button key={v} className={tab===v?'active':''}onClick={()=>setTab(v)}>{l}</button>)}</nav>
  {summaryError&&<div className="prop-warning">{summaryError}<button onClick={loadSummary}>Tentar novamente</button></div>}
  <section className="prop-kpis">{cards.map(([label,key])=><div style={box}key={key}><small>{label}</small><strong style={{display:'block',fontSize:23}}>{summaryLoading&&!summary?'…':fmt(summary?.[key])}</strong>{summary?.[`${key}_status`]?.startsWith('NOT_CALCULABLE')&&<small>Não calculável sob a meta de performance — não é zero.</small>}</div>)}</section>
  {tab==='catalogo'&&<>
   <section className="prop-section"style={box}><div className="prop-filters"><input aria-label="Busca"placeholder="Código CAR, nome cadastral ou município"value={form.q}onChange={e=>setForm({...form,q:e.target.value})}/><BrazilUfSelect value={form.uf}onChange={v=>setForm({...form,uf:v})}showAllLabel="Todas as UFs"/><input aria-label="Município"placeholder="Município"value={form.municipio}onChange={e=>setForm({...form,municipio:e.target.value})}/><input aria-label="Área mínima"type="number"placeholder="Área mínima (ha)"value={form.area_min}onChange={e=>setForm({...form,area_min:e.target.value})}/><input aria-label="Área máxima"type="number"placeholder="Área máxima (ha)"value={form.area_max}onChange={e=>setForm({...form,area_max:e.target.value})}/><select aria-label="Qualidade geográfica"value={form.geographic_quality}onChange={e=>setForm({...form,geographic_quality:e.target.value})}><option value="">Toda qualidade geográfica</option><option value="PROPERTY_COORDINATE">Coordenada própria válida</option><option value="MISSING">Coordenada ausente</option><option value="INVALID">Coordenada inválida</option></select><select aria-label="Contexto veterinário municipal"value={form.cobertura_veterinaria}onChange={e=>setForm({...form,cobertura_veterinaria:e.target.value})}><option value="">Todo contexto municipal</option>{Object.entries(coverage).filter(([v])=>v!=='INDISPONIVEL').map(([v,l])=><option key={v}value={v}>{l}</option>)}</select><select aria-label="Situação cadastral"disabled><option>Situação cadastral não disponível</option></select></div><div className="prop-actions"><button onClick={clear}>Limpar filtros</button><button className="primary"onClick={apply}>Aplicar filtros</button><span>{active} filtros ativos</span><select aria-label="Registros por página"value={pageSize}onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}>{[25,50,100].map(v=><option key={v}>{v}</option>)}</select></div></section>
   {enrichment?.status==='UNAVAILABLE'&&<div className="prop-warning">Contexto territorial temporariamente indisponível — {enrichment.reason}. Os registros SICAR/CAR continuam disponíveis.</div>}{listError&&<div className="prop-warning">{listError}<button onClick={loadList}>Tentar novamente</button></div>}<p>{listLoading?'Carregando catálogo…':`${fmt(total)} registros SICAR/CAR no recorte`}</p>
   <div className="prop-table"style={box}><table><thead><tr>{['Identificador','Município/UF','Área declarada','Situação cadastral','Qualidade geográfica','Fonte','Contexto municipal',''].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{items.map(i=><tr key={i.detail_id}><td><strong>{i.identifier||'Identificador indisponível'}</strong></td><td>{i.municipio||'—'}/{i.uf||'—'}</td><td>{typeof i.area_ha==='number'?`${fmt(i.area_ha)} ha`:'Não disponível'}</td><td>{i.registration_status_status==='NOT_AVAILABLE'?'Não disponível na fonte':i.registration_status}</td><td><span className="prop-badge">{geo[i.geographic_quality]||i.geographic_quality}</span></td><td>SICAR/CAR<br/><small>{i.source_object}</small></td><td>{i.municipal_context?<><b>Contexto municipal: {coverage[i.municipal_context.classificacao_veterinaria]||i.municipal_context.classificacao_veterinaria}</b><br/><small>Ligação por código IBGE</small></>:'Contexto temporariamente indisponível'}</td><td><button onClick={()=>nav(`/agro/propriedades/${encodeURIComponent(i.detail_id)}`)}>Detalhe</button></td></tr>)}</tbody></table></div>
   <div className="prop-mobile">{items.map(i=><article style={box}key={i.detail_id}><strong>{i.identifier||'Identificador indisponível'}</strong><p>{i.municipio||'—'}/{i.uf||'—'}</p><p>{typeof i.area_ha==='number'?`${fmt(i.area_ha)} ha declarados`:'Área não disponível'} · SICAR/CAR</p><button onClick={()=>nav(`/agro/propriedades/${encodeURIComponent(i.detail_id)}`)}>Detalhe</button></article>)}</div><div className="prop-actions"style={{justifyContent:'center'}}><button disabled={page<=1}onClick={()=>setPage(p=>p-1)}>Anterior</button><b>Página {page} de {fmt(pages)}</b><button disabled={page>=pages||page>=1000}onClick={()=>setPage(p=>p+1)}>Próxima</button></div>
  </>}
  {tab==='territorio'&&<section className="prop-section"style={box}><h3>Contexto territorial municipal</h3><p>Os indicadores abaixo descrevem municípios. Eles não são atributos de um imóvel rural individual.</p><div className="prop-actions"><BrazilUfSelect value={filters.uf}onChange={v=>setFilters({...filters,uf:v})}showAllLabel="Todo o Brasil"/><input placeholder="Município"value={filters.municipio}onChange={e=>setFilters({...filters,municipio:e.target.value})}/></div>{contextError?<div className="prop-warning">{contextError}<button onClick={loadContext}>Tentar novamente</button></div>:contextLoading?<p>Carregando contexto…</p>:<div className="prop-table"><table><thead><tr>{['Município/UF','Código IBGE','Imóveis registrados','Rebanho municipal','Presença técnica conhecida','Classificação municipal','Fonte','Links'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{context.map(x=><tr key={x.codigo_ibge}><td>{x.municipio}/{x.uf}</td><td>{x.codigo_ibge}</td><td>{fmt(x.imoveis_registrados)}</td><td>{fmt(x.rebanho_municipal)}</td><td>{fmt(x.presenca_tecnica_conhecida_75km)}</td><td>{coverage[x.classificacao_veterinaria]||x.classificacao_veterinaria}</td><td>SICAR/CAR + contexto municipal<br/><small>IBGE_CODE_EXACT</small></td><td><Link to={`/agro/deserto-veterinario?uf=${x.uf}&q=${encodeURIComponent(x.municipio)}`}>Deserto Veterinário</Link> · <Link to={`/agro/tecnica?tab=territorio&uf=${x.uf}`}>Canal Técnico</Link> · <Link to={`/agro/oportunidades?uf=${x.uf}`}>Oportunidades</Link> · <Link to={`/agro/logistica?uf=${x.uf}`}>Agro-Logística</Link></td></tr>)}</tbody></table></div>}</section>}
  {tab==='mapa'&&<section className="prop-section"style={box}><h3>Recorte cartográfico de registros SICAR/CAR</h3><p>O mapa retorna no máximo 1.000 pontos dentro do viewport. Não representa todos os imóveis e não comprova atividade produtiva.</p>{mapError?<div className="prop-warning">{mapError}<button onClick={loadMap}>Tentar novamente</button></div>:mapLoading?<p>Carregando mapa…</p>:<MapContainer className="prop-map"center={[-14.2,-51.9]}zoom={4}minZoom={3}maxBounds={[[-33.75,-73.99],[5.27,-34.79]]}style={{height:520,width:'100%'}}><TileLayer attribution="&copy; OpenStreetMap"url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{points.filter(x=>x.latitude>=-33.75&&x.latitude<=5.27&&x.longitude>=-73.99&&x.longitude<=-34.79).map(x=><CircleMarker key={x.detail_id}center={[x.latitude,x.longitude]}radius={4}pathOptions={{color:'#166534',fillOpacity:.55}}><Tooltip><b>Registro SICAR/CAR</b><br/>{x.municipio}/{x.uf}<br/>Área declarada: {typeof x.area_ha==='number'?`${fmt(x.area_ha)} ha`:'Não disponível'}<br/><Link to={`/agro/propriedades/${x.detail_id}`}>Ver detalhe</Link></Tooltip></CircleMarker>)}</MapContainer>}<p>{fmt(points.length)} registros retornados · total nacional não calculado nesta consulta para preservar performance.</p></section>}
  {tab==='metodologia'&&<section className="prop-section"style={box}><h3>Como interpretar o catálogo</h3><dl><dt>Registro SICAR/CAR</dt><dd>Cadastro declaratório de imóvel rural. Não comprova propriedade produtiva, atividade econômica, demanda ou disponibilidade comercial.</dd><dt>Área declarada</dt><dd>Valor em hectares informado no cadastro; não representa área produtiva nem soma territorial sem sobreposição.</dd><dt>Coordenada própria do registro</dt><dd>Coordenada associada ao imóvel no cadastro e validada apenas contra os limites do Brasil. Não substitui geometria ou limite fundiário.</dd><dt>Contexto municipal</dt><dd>Rebanho, presença técnica e classificação veterinária pertencem ao município ligado por código IBGE exato — nunca ao imóvel individual.</dd><dt>Situação cadastral</dt><dd>Não está disponível na fonte atual. O campo comercial interno não é apresentado como situação oficial do CAR.</dd><dt>Ausência de contexto</dt><dd>É exibida como indisponível ou não calculável, nunca como zero.</dd></dl><h3>Proveniência</h3><p>Fonte funcional: SICAR/CAR. Objeto canônico: <code>prospeccao.imovel_rural</code>. Contexto municipal: <code>prospeccao.v_white_space_pecuaria</code>.</p></section>}
  <p className="property-legal-note">Imóvel rural registrado não equivale a fazenda produtiva, produtor identificado ou operação economicamente ativa.</p>
 </AgroPageShell>
}
