import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {CircleMarker,MapContainer,TileLayer,Tooltip} from 'react-leaflet';
import {BrazilUfSelect} from '../components/territorial/BrazilUfSelect';
import AgroPageShell from '../components/AgroPageShell';
import {httpClient} from '../services/http/client';
import {AGRO_API} from './agroApiEndpoints';
import 'leaflet/dist/leaflet.css';

const tabs=[['resumo','Visão Geral'],['profissionais','Profissionais'],['estabelecimentos','Estabelecimentos'],['territorio','Cobertura Territorial'],['metodologia','Metodologia']] as const;
const typeLabel:Record<string,string>={PROFISSIONAL_NOMINAL:'Profissional nominal',ESTABELECIMENTO_VETERINARIO:'Estabelecimento veterinário',PROVAVEL_POR_CNAE:'Inferido pelo CNAE',REPRODUCAO_MANEJO:'Reprodução/manejo',AGRONOMO_CREA:'Profissional de origem CREA',ORIGEM_ABCZ:'Profissional de origem ABCZ'};
const evidenceLabel:Record<string,string>={CADASTRO_INTERNO:'Identificado nominalmente',REGISTRO_CONSELHO_INFORMADO:'Registro de conselho informado',ESTABELECIMENTO_EMPRESARIAL:'Estabelecimento cadastral',INFERIDO_POR_CNAE:'Inferido pelo CNAE'};
const originLabel:Record<string,string>={CADASTRO_INTERNO:'Base integrada Canal Técnico',REGISTRO_CONSELHO_INFORMADO:'Conselho informado',INFERIDO_POR_CNAE:'Cadastro empresarial/CNAE',CREA:'CREA',ABCZ:'ABCZ'};
const box:React.CSSProperties={background:'var(--bg-surface)',border:'1px solid var(--border-default)',borderRadius:10,padding:14};
const fmt=(v:any)=>typeof v==='number'?v.toLocaleString('pt-BR'):'—';
const blank={q:'',uf:'',municipio:'',profissao:'',origem:'',evidencia:'',com_crmv:'',contact_status:'ANY',atividade:''};
const contact=(i:any)=>i.contact_status==='NONE'?'Sem contato conhecido':i.contact_attribution==='INSTITUTIONAL'?'Contato institucional':'Contato não atribuído';
const phone=(v:any)=>{const n=String(v||'').replace(/\D/g,'');return n.length===11?`(${n.slice(0,2)}) ${n.slice(2,7)}-${n.slice(7)}`:v||null};

export default function AgroTecnicaApproved(){
 const[query,setQuery]=useSearchParams(); const tab=(tabs.some(([v])=>v===query.get('tab'))?query.get('tab'):'resumo') as string;
 const[items,setItems]=useState<any[]>([]),[stats,setStats]=useState<any>(null),[map,setMap]=useState<any[]>([]);
 const[listLoading,setListLoading]=useState(false),[statsLoading,setStatsLoading]=useState(false),[mapLoading,setMapLoading]=useState(false);
 const[listError,setListError]=useState<string|null>(null),[statsError,setStatsError]=useState<string|null>(null),[mapError,setMapError]=useState<string|null>(null);
 const[page,setPage]=useState(Number(query.get('page'))||1),[pageSize,setPageSize]=useState(Number(query.get('page_size'))||25),[total,setTotal]=useState(0),[pages,setPages]=useState(0);
 const[form,setForm]=useState<any>(()=>({...blank,...Object.fromEntries(Object.keys(blank).map(k=>[k,query.get(k)||blank[k as keyof typeof blank]]))}));
 const[filters,setFilters]=useState<any>(form),[metric,setMetric]=useState('profissionais_nominais');
 const setTab=(value:string)=>{const q=new URLSearchParams(query);q.set('tab',value);q.delete('page');setQuery(q);setPage(1)};
 const loadStats=useCallback(async()=>{setStatsLoading(true);setStatsError(null);const[r]=await Promise.allSettled([httpClient.get(AGRO_API.tecnicosStats)]);if(r.status==='fulfilled')setStats(r.value.data);else setStatsError('Os indicadores estão temporariamente indisponíveis. A lista continua independente.');setStatsLoading(false)},[]);
 const loadList=useCallback(async()=>{if(!['profissionais','estabelecimentos'].includes(tab))return;setListLoading(true);setListError(null);const params:any={page,page_size:pageSize,grupo:tab==='profissionais'?'PROFISSIONAIS':'ESTABELECIMENTOS'};Object.entries(filters).forEach(([k,v])=>{if(v!==''&&v!=='ANY')params[k]=v});const[r]=await Promise.allSettled([httpClient.get(AGRO_API.tecnicos,{params})]);if(r.status==='fulfilled'){setItems(r.value.data.items||[]);setTotal(r.value.data.total||0);setPages(r.value.data.total_pages||0)}else setListError('Não foi possível carregar os registros deste recorte. Os indicadores preservados continuam visíveis.');setListLoading(false)},[filters,page,pageSize,tab]);
 const loadMap=useCallback(async()=>{if(tab!=='territorio')return;setMapLoading(true);setMapError(null);const[r]=await Promise.allSettled([httpClient.get(AGRO_API.tecnicosMapa,{params:{uf:filters.uf||undefined,limit:5570}})]);if(r.status==='fulfilled')setMap(r.value.data.items||[]);else setMapError('A cobertura municipal está temporariamente indisponível; nenhuma ausência territorial foi inferida.');setMapLoading(false)},[filters.uf,tab]);
 useEffect(()=>{loadStats()},[loadStats]);useEffect(()=>{loadList()},[loadList]);useEffect(()=>{loadMap()},[loadMap]);
 const apply=()=>{setFilters({...form});setPage(1);const q=new URLSearchParams();q.set('tab',tab);q.set('page_size',String(pageSize));Object.entries(form).forEach(([k,v])=>{if(v&&v!=='ANY')q.set(k,String(v))});setQuery(q)};
 const clear=()=>{setForm({...blank});setFilters({...blank});setPage(1);setQuery({tab})};
 const active=Object.entries(form).filter(([,v])=>v!==''&&v!=='ANY').length;
 const options=(key:string)=>Array.isArray(stats?.[key])?stats[key]:[];
 const maxMap=useMemo(()=>Math.max(1,...map.map(x=>Number(x[metric])||0)),[map,metric]);
 const cards=[['Registros no canal','total'],['Profissionais nominais','profissionais_nominais'],['Estabelecimentos','estabelecimentos_veterinarios'],['Veterinários identificados','veterinarios'],['Zootecnistas identificados','zootecnistas'],['Reprodução/manejo','reproducao_manejo'],['CRMV informado','com_crmv_informado'],['Registros com contato','com_contato']];
 return <AgroPageShell title="Canal Técnico & Cobertura de Assistência" subtitle="Profissionais, estabelecimentos e atividades técnicas identificados em fontes integradas, com origem e nível de evidência explícitos.">
  <style>{`.tech-tabs{display:flex;gap:8px;overflow:auto}.tech-tabs button{white-space:nowrap}.tech-tabs .active{background:#0f766e;color:white}.tech-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(165px,1fr));gap:10px}.tech-filters{display:grid;grid-template-columns:repeat(4,minmax(145px,1fr));gap:9px}.tech-actions{display:flex;align-items:center;gap:9px;flex-wrap:wrap;margin-top:10px}.tech-table{overflow:auto}.tech-table table{min-width:960px;width:100%}.tech-mobile{display:none}.tech-section{margin-top:14px}.tech-badge{display:inline-block;padding:3px 7px;border-radius:999px;background:rgba(20,184,166,.13);font-size:12px}.tech-warning{padding:10px;border-left:3px solid #f59e0b;background:rgba(245,158,11,.08)}@media(max-width:700px){.tech-filters{grid-template-columns:1fr 1fr}.tech-table{display:none}.tech-mobile{display:grid;gap:10px}.tech-kpis{grid-template-columns:1fr 1fr}.tech-map{height:390px!important}}`}</style>
  <nav className="tech-tabs" aria-label="Seções do Canal Técnico">{tabs.map(([v,l])=><button key={v} className={tab===v?'active':''} onClick={()=>setTab(v)}>{l}</button>)}</nav>
  {tab==='resumo'&&<>
   {statsError&&<div className="tech-warning">{statsError}<button onClick={loadStats}>Tentar novamente</button></div>}
   <section className="tech-kpis tech-section">{cards.map(([label,key])=><div style={box} key={key}><small>{label}</small><strong style={{display:'block',fontSize:24}}>{statsLoading&&!stats?'…':fmt(stats?.[key])}</strong></div>)}</section>
   <section className="tech-section" style={box}><h3>Composição da base</h3><p>Profissionais nominais, estabelecimentos, atividades de reprodução/manejo e registros de origem institucional são apresentados como naturezas diferentes.</p><div className="tech-kpis">{[['Profissionais nominais','profissionais_nominais'],['Estabelecimentos veterinários','estabelecimentos_veterinarios'],['Inferidos por CNAE','provaveis_por_cnae'],['Origem CREA','origem_crea'],['Origem ABCZ','origem_abcz']].map(([l,k])=><div key={k}><small>{l}</small><strong style={{display:'block'}}>{fmt(stats?.[k])}</strong></div>)}</div></section>
   <section className="tech-section" style={box}><h3>Evidência dos registros</h3><div className="tech-kpis">{[['Identificado nominalmente','evidencia_cadastro_interno'],['Conselho informado','evidencia_conselho_informado'],['Estabelecimento cadastral','evidencia_estabelecimento'],['Inferido pelo CNAE','evidencia_inferido_cnae']].map(([l,k])=><div key={k}><small>{l}</small><strong style={{display:'block'}}>{fmt(stats?.[k])}</strong></div>)}</div><p className="tech-warning">As categorias descrevem a evidência encontrada; não formam um score de qualidade.</p></section>
  </>}
  {['profissionais','estabelecimentos'].includes(tab)&&<>
   <section className="tech-section" style={box}><div className="tech-filters"><input aria-label="Busca" placeholder="Nome, CNPJ ou município" value={form.q} onChange={e=>setForm({...form,q:e.target.value})}/><BrazilUfSelect value={form.uf} onChange={v=>setForm({...form,uf:v})} showAllLabel="Todas as UFs"/><input aria-label="Município" placeholder="Município" value={form.municipio} onChange={e=>setForm({...form,municipio:e.target.value})}/><select aria-label="Profissão" value={form.profissao} onChange={e=>setForm({...form,profissao:e.target.value})}><option value="">Todas as profissões</option>{options('profissoes').map((v:string)=><option key={v}>{v}</option>)}</select><select aria-label="Evidência" value={form.evidencia} onChange={e=>setForm({...form,evidencia:e.target.value})}><option value="">Toda evidência</option>{options('evidencias').map((v:string)=><option value={v} key={v}>{evidenceLabel[v]||v}</option>)}</select><select aria-label="Origem" value={form.origem} onChange={e=>setForm({...form,origem:e.target.value})}><option value="">Todas as origens</option>{options('origens').map((v:string)=><option value={v} key={v}>{originLabel[v]||v}</option>)}</select><select aria-label="Atividade" value={form.atividade} onChange={e=>setForm({...form,atividade:e.target.value})}><option value="">Todas as atividades</option>{options('atividades').map((v:string)=><option key={v}>{v}</option>)}</select><select aria-label="CRMV informado" value={form.com_crmv} onChange={e=>setForm({...form,com_crmv:e.target.value})}><option value="">CRMV: todos</option><option value="true">CRMV informado</option><option value="false">Sem CRMV informado</option></select><select aria-label="Contato" value={form.contact_status} onChange={e=>setForm({...form,contact_status:e.target.value})}><option value="ANY">Qualquer contato</option><option value="PHONE">Telefone</option><option value="EMAIL">E-mail</option><option value="BOTH">Telefone e e-mail</option><option value="NONE">Sem contato conhecido</option></select></div><div className="tech-actions"><button onClick={clear}>Limpar filtros</button><button className="primary" onClick={apply}>Aplicar filtros</button><span>{active} filtros ativos</span><select aria-label="Itens por página" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}>{[25,50,100].map(v=><option key={v}>{v}</option>)}</select></div></section>
   {listError&&<div className="tech-warning">{listError}<button onClick={loadList}>Tentar novamente</button></div>}<p>{listLoading?'Carregando…':`${fmt(total)} registros no recorte`}</p>
   <div className="tech-table" style={box}><table><thead><tr>{(tab==='profissionais'?['Nome','Profissão','Município/UF','CRMV informado','Evidência','Origem','Contato','']:['Razão social / identificação','Natureza','Atividade / CNAE','Município/UF','Evidência','Contato institucional','Origem','']).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.nome||'Estabelecimento sem nome disponível'}</td>{tab==='profissionais'?<><td>{i.profissao||'Não informada'}</td><td>{i.municipio||'—'}/{i.uf||'—'}</td><td>{i.crmv_informado?<span title="O número foi encontrado na fonte de origem, mas a situação profissional não foi validada oficialmente pelo WiNS Hub.">Informado · não validado</span>:'Não informado'}</td><td><span className="tech-badge">{evidenceLabel[i.evidence_type]||i.evidence_type}</span></td><td>{originLabel[i.profissao_origem]||i.profissao_origem}</td><td>{contact(i)}<br/><small>{phone(i.telefone)||String(i.email||'').toLowerCase()||'—'}</small></td></>:<><td>{typeLabel[i.entidade_tipo]||i.entidade_tipo}</td><td>{i.atividade||'—'}{i.cnae?` · ${i.cnae}`:''}</td><td>{i.municipio||'—'}/{i.uf||'—'}</td><td><span className="tech-badge">{evidenceLabel[i.evidence_type]||i.evidence_type}</span></td><td>{contact(i)}<br/><small>{phone(i.telefone)||String(i.email||'').toLowerCase()||'—'}</small></td><td>{originLabel[i.profissao_origem]||i.profissao_origem}</td></>}<td><Link to={`/agro/tecnica/${encodeURIComponent(i.id)}`}>Detalhe</Link></td></tr>)}</tbody></table></div>
   <div className="tech-mobile">{items.map(i=><article style={box} key={i.id}><strong>{i.nome||'Estabelecimento sem nome disponível'}</strong><p>{tab==='profissionais'?(i.profissao||'Profissão não informada'):(i.atividade||typeLabel[i.entidade_tipo])}</p><p>{i.municipio||'—'}/{i.uf||'—'} · {contact(i)}</p><Link to={`/agro/tecnica/${encodeURIComponent(i.id)}`}>Ver detalhe</Link></article>)}</div>
   <div className="tech-actions" style={{justifyContent:'center'}}><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page} de {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Próxima</button></div>
  </>}
  {tab==='territorio'&&<section className="tech-section" style={box}><h3>Cobertura técnica conhecida — recorte municipal</h3><p>Presença conhecida na base; não representa cobertura oficial completa nem disponibilidade de atendimento.</p><div className="tech-actions"><BrazilUfSelect value={filters.uf} onChange={v=>setFilters({...filters,uf:v})} showAllLabel="Todo o Brasil"/><select aria-label="Métrica territorial" value={metric} onChange={e=>setMetric(e.target.value)}><option value="profissionais_nominais">Profissionais</option><option value="veterinarios">Veterinários</option><option value="zootecnistas">Zootecnistas</option><option value="estabelecimentos">Estabelecimentos</option><option value="reproducao_manejo">Reprodução/manejo</option></select></div>{mapError?<div className="tech-warning">{mapError}<button onClick={loadMap}>Tentar novamente</button></div>:mapLoading?<p>Carregando mapa…</p>:<MapContainer className="tech-map" center={[-14.2,-51.9]} zoom={4} minZoom={3} maxBounds={[[-33.75,-73.99],[5.27,-34.79]]} style={{height:520,width:'100%'}}><TileLayer attribution="&copy; OpenStreetMap" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{map.map(x=><CircleMarker key={x.codigo_ibge} center={[Number(x.latitude),Number(x.longitude)]} radius={4+12*Math.sqrt((Number(x[metric])||0)/maxMap)} pathOptions={{color:'#0f766e',fillColor:'#14b8a6',fillOpacity:.62}}><Tooltip><b>{x.municipio}/{x.uf}</b><br/>Presença conhecida: {fmt(x[metric])}<br/>Rebanho municipal: {fmt(x.rebanho_municipal)}<br/>Classificação publicada: {x.classificacao_territorial||'—'}<br/><Link to={`/agro/deserto-veterinario?uf=${x.uf}&q=${encodeURIComponent(x.municipio)}`}>Ver Deserto Veterinário</Link></Tooltip></CircleMarker>)}</MapContainer>}<p><b>{fmt(map.length)}</b> municípios retornados · ligação <code>MUNICIPAL_NAME_NORMALIZED</code>, sem fuzzy matching silencioso.</p></section>}
  {tab==='metodologia'&&<section className="tech-section" style={box}><h3>Como interpretar esta base</h3><dl><dt>Profissional nominal</dt><dd>Pessoa identificada nominalmente em uma fonte integrada; isso não comprova disponibilidade de atendimento.</dd><dt>Estabelecimento veterinário</dt><dd>Registro empresarial/cadastral. Contatos são institucionais e não devem ser atribuídos a uma pessoa.</dd><dt>Inferido pelo CNAE</dt><dd>Natureza provável derivada da atividade empresarial, não um profissional comprovado.</dd><dt>Reprodução/manejo</dt><dd>Atividade relacionada identificada na base, sem inferência automática de habilitação profissional.</dd><dt>CRMV informado</dt><dd>O número foi encontrado na fonte, mas não foi validado oficialmente pelo WiNS Hub.</dd><dt>Ausência de registro</dt><dd>Não significa ausência de profissional ou assistência técnica no território.</dd></dl><h3>Fontes e proveniência</h3><p>A interface usa rótulos amigáveis. O detalhe preserva os objetos técnicos canônicos, incluindo <code>prospeccao.v_tecnico_full</code>, <code>prospeccao.tecnico_crea</code>, <code>prospeccao.canal_central</code> e cadastros empresariais integrados.</p><p>Nenhum score é apresentado porque não existe metodologia comprovada para um ranking numérico.</p></section>}
 </AgroPageShell>
}
