 CREATE OR REPLACE FUNCTION engenharia.detectar_conflito(p_grupo_id uuid, p_campo_canonico_id text, p_valor_a text, p_valor_b text, p_fonte_a_id integer DEFAULT NULL::integer, p_fonte_b_id integer DEFAULT NULL::integer, p_captura_a_id uuid DEFAULT NULL::uuid, p_captura_b_id uuid DEFAULT NULL::uuid, p_tipo_conflito text DEFAULT NULL::text)+
  RETURNS uuid                                                                                                                                                                                                                                                                                                                                      +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                  +
  SET search_path TO 'wins_v2', 'pg_temp'                                                                                                                                                                                                                                                                                                           +
 AS $function$                                                                                                                                                                                                                                                                                                                                      +
 DECLARE                                                                                                                                                                                                                                                                                                                                            +
     v_conflito_id UUID;                                                                                                                                                                                                                                                                                                                            +
     v_tipo_conflito TEXT;                                                                                                                                                                                                                                                                                                                          +
     v_categoria TEXT;                                                                                                                                                                                                                                                                                                                              +
 BEGIN                                                                                                                                                                                                                                                                                                                                              +
     IF p_tipo_conflito IS NOT NULL THEN                                                                                                                                                                                                                                                                                                            +
         v_tipo_conflito := p_tipo_conflito;                                                                                                                                                                                                                                                                                                        +
     ELSE                                                                                                                                                                                                                                                                                                                                           +
         SELECT cc.categoria INTO v_categoria                                                                                                                                                                                                                                                                                                       +
         FROM campos_canonicos cc                                                                                                                                                                                                                                                                                                                   +
         WHERE cc.id = p_campo_canonico_id;                                                                                                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                                                                                    +
         v_tipo_conflito := CASE                                                                                                                                                                                                                                                                                                                    +
             WHEN v_categoria IS NOT NULL AND v_categoria IN (                                                                                                                                                                                                                                                                                      +
                 'identificacao', 'localizacao', 'entidade', 'valor',                                                                                                                                                                                                                                                                               +
                 'descricao', 'data', 'papel', 'fase'                                                                                                                                                                                                                                                                                               +
             ) THEN                                                                                                                                                                                                                                                                                                                                 +
                 CASE v_categoria                                                                                                                                                                                                                                                                                                                   +
                     WHEN 'identificacao' THEN 'identificador'                                                                                                                                                                                                                                                                                      +
                     WHEN 'localizacao' THEN 'localizacao'                                                                                                                                                                                                                                                                                          +
                     WHEN 'entidade' THEN 'entidade'                                                                                                                                                                                                                                                                                                +
                     WHEN 'valor' THEN 'valor'                                                                                                                                                                                                                                                                                                      +
                     WHEN 'descricao' THEN 'descricao_tecnica'                                                                                                                                                                                                                                                                                      +
                     WHEN 'data' THEN 'data'                                                                                                                                                                                                                                                                                                        +
                     WHEN 'papel' THEN 'papel'                                                                                                                                                                                                                                                                                                      +
                     WHEN 'fase' THEN 'fase'                                                                                                                                                                                                                                                                                                        +
                 END                                                                                                                                                                                                                                                                                                                                +
             WHEN p_campo_canonico_id LIKE 'CC-0%' THEN 'valor'                                                                                                                                                                                                                                                                                     +
             WHEN p_campo_canonico_id LIKE 'CC-01%' THEN 'valor'                                                                                                                                                                                                                                                                                    +
             WHEN p_campo_canonico_id LIKE 'CC-02%' THEN 'entidade'                                                                                                                                                                                                                                                                                 +
             WHEN p_campo_canonico_id LIKE 'CC-03%' THEN 'localizacao'                                                                                                                                                                                                                                                                              +
             WHEN p_campo_canonico_id LIKE 'CC-04%' THEN 'descricao_tecnica'                                                                                                                                                                                                                                                                        +
             ELSE 'valor'                                                                                                                                                                                                                                                                                                                           +
         END;                                                                                                                                                                                                                                                                                                                                       +
     END IF;                                                                                                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                                                                                                                    +
     IF semanticamente_compativel(p_campo_canonico_id, p_valor_a, p_valor_b) THEN                                                                                                                                                                                                                                                                   +
         INSERT INTO auditoria_consolidacao (grupo_id, campo_canonico_id, acao, detalhes)                                                                                                                                                                                                                                                           +
         VALUES (p_grupo_id, p_campo_canonico_id, 'conflito_ignorado',                                                                                                                                                                                                                                                                              +
                 jsonb_build_object(                                                                                                                                                                                                                                                                                                                +
                     'motivo', 'valores_semanticamente_compativeis',                                                                                                                                                                                                                                                                                +
                     'valor_a', p_valor_a,                                                                                                                                                                                                                                                                                                          +
                     'valor_b', p_valor_b,                                                                                                                                                                                                                                                                                                          +
                     'tipo', v_tipo_conflito                                                                                                                                                                                                                                                                                                        +
                 ));                                                                                                                                                                                                                                                                                                                                +
         RETURN NULL;                                                                                                                                                                                                                                                                                                                               +
     END IF;                                                                                                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                                                                                                                    +
     SELECT fc.id INTO v_conflito_id                                                                                                                                                                                                                                                                                                                +
     FROM conflitos_campos fc                                                                                                                                                                                                                                                                                                                       +
     WHERE fc.grupo_id = p_grupo_id                                                                                                                                                                                                                                                                                                                 +
       AND fc.campo_canonico_id = p_campo_canonico_id                                                                                                                                                                                                                                                                                               +
       AND (                                                                                                                                                                                                                                                                                                                                        +
         (fc.valor_a = p_valor_a AND fc.valor_b = p_valor_b) OR                                                                                                                                                                                                                                                                                     +
         (fc.valor_a = p_valor_b AND fc.valor_b = p_valor_a)                                                                                                                                                                                                                                                                                        +
       )                                                                                                                                                                                                                                                                                                                                            +
       AND fc.estado = 'ABERTO'                                                                                                                                                                                                                                                                                                                     +
     LIMIT 1;                                                                                                                                                                                                                                                                                                                                       +
                                                                                                                                                                                                                                                                                                                                                    +
     IF v_conflito_id IS NOT NULL THEN                                                                                                                                                                                                                                                                                                              +
         RETURN v_conflito_id;                                                                                                                                                                                                                                                                                                                      +
     END IF;                                                                                                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                                                                                                                    +
     INSERT INTO conflitos_campos (grupo_id, campo_canonico_id, valor_a, valor_b,                                                                                                                                                                                                                                                                   +
                                    fonte_a_id, fonte_b_id, captura_a_id, captura_b_id,                                                                                                                                                                                                                                                             +
                                    tipo_conflito)                                                                                                                                                                                                                                                                                                  +
     VALUES (p_grupo_id, p_campo_canonico_id, p_valor_a, p_valor_b,                                                                                                                                                                                                                                                                                 +
             p_fonte_a_id, p_fonte_b_id, p_captura_a_id, p_captura_b_id,                                                                                                                                                                                                                                                                            +
             v_tipo_conflito)                                                                                                                                                                                                                                                                                                                       +
     RETURNING id INTO v_conflito_id;                                                                                                                                                                                                                                                                                                               +
                                                                                                                                                                                                                                                                                                                                                    +
     INSERT INTO auditoria_consolidacao (grupo_id, campo_canonico_id, acao, detalhes)                                                                                                                                                                                                                                                               +
     VALUES (p_grupo_id, p_campo_canonico_id, 'conflito_detectado',                                                                                                                                                                                                                                                                                 +
             jsonb_build_object(                                                                                                                                                                                                                                                                                                                    +
                 'conflito_id', v_conflito_id,                                                                                                                                                                                                                                                                                                      +
                 'tipo', v_tipo_conflito,                                                                                                                                                                                                                                                                                                           +
                 'valor_a', p_valor_a,                                                                                                                                                                                                                                                                                                              +
                 'valor_b', p_valor_b                                                                                                                                                                                                                                                                                                               +
             ));                                                                                                                                                                                                                                                                                                                                    +
                                                                                                                                                                                                                                                                                                                                                    +
     RETURN v_conflito_id;                                                                                                                                                                                                                                                                                                                          +
 END;                                                                                                                                                                                                                                                                                                                                               +
 $function$                                                                                                                                                                                                                                                                                                                                         +
 

