 CREATE OR REPLACE FUNCTION engenharia.registrar_captura(p_captador_nome text, p_fonte_nome text, p_payload jsonb, p_id_externo text DEFAULT NULL::text, p_url_origem text DEFAULT NULL::text, p_versao_captador text DEFAULT NULL::text)+
  RETURNS uuid                                                                                                                                                                                                                           +
  LANGUAGE plpgsql                                                                                                                                                                                                                       +
  SET search_path TO 'wins_v2', 'pg_temp'                                                                                                                                                                                                +
 AS $function$                                                                                                                                                                                                                           +
 DECLARE                                                                                                                                                                                                                                 +
     v_captador_id INT;                                                                                                                                                                                                                  +
     v_fonte_id    INT;                                                                                                                                                                                                                  +
     v_hash        TEXT;                                                                                                                                                                                                                 +
     v_captura_id  UUID;                                                                                                                                                                                                                 +
 BEGIN                                                                                                                                                                                                                                   +
     SELECT id INTO v_captador_id FROM captadores WHERE nome = p_captador_nome;                                                                                                                                                          +
     IF NOT FOUND THEN                                                                                                                                                                                                                   +
         RAISE EXCEPTION 'Captador nao encontrado: %', p_captador_nome;                                                                                                                                                                  +
     END IF;                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                         +
     SELECT id INTO v_fonte_id FROM fontes WHERE nome = p_fonte_nome;                                                                                                                                                                    +
     IF NOT FOUND THEN                                                                                                                                                                                                                   +
         RAISE EXCEPTION 'Fonte nao encontrada: %', p_fonte_nome;                                                                                                                                                                        +
     END IF;                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                         +
     v_hash := encode(sha256(p_payload::text::bytea), 'hex');                                                                                                                                                                            +
                                                                                                                                                                                                                                         +
     INSERT INTO capturas_brutas (captador_id, fonte_id, payload, id_externo, url_origem, hash_conteudo, versao_captador)                                                                                                                +
     VALUES (v_captador_id, v_fonte_id, p_payload, p_id_externo, p_url_origem, v_hash, p_versao_captador)                                                                                                                                +
     ON CONFLICT (captador_id, hash_conteudo) DO UPDATE                                                                                                                                                                                  +
         SET processado_em = now(),                                                                                                                                                                                                      +
             status = 'bruto'                                                                                                                                                                                                            +
     RETURNING id INTO v_captura_id;                                                                                                                                                                                                     +
                                                                                                                                                                                                                                         +
     RETURN v_captura_id;                                                                                                                                                                                                                +
 END;                                                                                                                                                                                                                                    +
 $function$                                                                                                                                                                                                                              +
 

