 CREATE OR REPLACE FUNCTION engenharia.upsert_entidade_lookup_minimo(p_cnpj text, p_razao_social text DEFAULT NULL::text, p_nome_fantasia text DEFAULT NULL::text, p_natureza text DEFAULT NULL::text, p_municipio text DEFAULT NULL::text, p_uf text DEFAULT NULL::text, p_fonte text DEFAULT NULL::text, p_captador text DEFAULT NULL::text)+
  RETURNS uuid                                                                                                                                                                                                                                                                                                                                +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                            +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                            +
  SET search_path TO 'wins_v2', 'public'                                                                                                                                                                                                                                                                                                      +
 AS $function$                                                                                                                                                                                                                                                                                                                                +
 DECLARE                                                                                                                                                                                                                                                                                                                                      +
     v_cnpj text := regexp_replace(COALESCE(p_cnpj, ''), '\D', '', 'g');                                                                                                                                                                                                                                                                      +
     v_id   uuid;                                                                                                                                                                                                                                                                                                                             +
     v_uf   text;                                                                                                                                                                                                                                                                                                                             +
 BEGIN                                                                                                                                                                                                                                                                                                                                        +
     IF v_cnpj IS NULL OR length(v_cnpj) <> 14 THEN                                                                                                                                                                                                                                                                                           +
         RETURN NULL;                                                                                                                                                                                                                                                                                                                         +
     END IF;                                                                                                                                                                                                                                                                                                                                  +
     IF NOT wins_v2.cnpj_dv_valido(v_cnpj) THEN                                                                                                                                                                                                                                                                                               +
         RETURN NULL;                                                                                                                                                                                                                                                                                                                         +
     END IF;                                                                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                                              +
     v_uf := NULLIF(upper(btrim(COALESCE(p_uf, ''))), '');                                                                                                                                                                                                                                                                                    +
     IF v_uf IS NOT NULL AND v_uf !~ '^[A-Z]{2}$' THEN                                                                                                                                                                                                                                                                                        +
         v_uf := NULL;                                                                                                                                                                                                                                                                                                                        +
     END IF;                                                                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                                              +
     INSERT INTO wins_v2.entidades_lookup (                                                                                                                                                                                                                                                                                                   +
         entidade_id,                                                                                                                                                                                                                                                                                                                         +
         cnpj_normalizado,                                                                                                                                                                                                                                                                                                                    +
         razao_social,                                                                                                                                                                                                                                                                                                                        +
         nome_fantasia,                                                                                                                                                                                                                                                                                                                       +
         natureza_entidade,                                                                                                                                                                                                                                                                                                                   +
         municipio,                                                                                                                                                                                                                                                                                                                           +
         uf,                                                                                                                                                                                                                                                                                                                                  +
         fontes,                                                                                                                                                                                                                                                                                                                              +
         captadores,                                                                                                                                                                                                                                                                                                                          +
         quantidade_ocorrencias,                                                                                                                                                                                                                                                                                                              +
         completude,                                                                                                                                                                                                                                                                                                                          +
         confianca,                                                                                                                                                                                                                                                                                                                           +
         necessita_enriquecimento_externo,                                                                                                                                                                                                                                                                                                    +
         importado_em                                                                                                                                                                                                                                                                                                                         +
     ) VALUES (                                                                                                                                                                                                                                                                                                                               +
         gen_random_uuid(),                                                                                                                                                                                                                                                                                                                   +
         v_cnpj,                                                                                                                                                                                                                                                                                                                              +
         NULLIF(btrim(COALESCE(p_razao_social, '')), ''),                                                                                                                                                                                                                                                                                     +
         NULLIF(btrim(COALESCE(p_nome_fantasia, '')), ''),                                                                                                                                                                                                                                                                                    +
         NULLIF(btrim(COALESCE(p_natureza, '')), ''),                                                                                                                                                                                                                                                                                         +
         NULLIF(btrim(COALESCE(p_municipio, '')), ''),                                                                                                                                                                                                                                                                                        +
         v_uf,                                                                                                                                                                                                                                                                                                                                +
         NULLIF(btrim(COALESCE(p_fonte, '')), ''),                                                                                                                                                                                                                                                                                            +
         NULLIF(btrim(COALESCE(p_captador, '')), ''),                                                                                                                                                                                                                                                                                         +
         1,                                                                                                                                                                                                                                                                                                                                   +
         'pipeline',                                                                                                                                                                                                                                                                                                                          +
         '0.80',                                                                                                                                                                                                                                                                                                                              +
         'SIM',                                                                                                                                                                                                                                                                                                                               +
         now()                                                                                                                                                                                                                                                                                                                                +
     )                                                                                                                                                                                                                                                                                                                                        +
     ON CONFLICT (cnpj_normalizado) DO UPDATE SET                                                                                                                                                                                                                                                                                             +
         razao_social = COALESCE(NULLIF(btrim(EXCLUDED.razao_social), ''), wins_v2.entidades_lookup.razao_social),                                                                                                                                                                                                                            +
         nome_fantasia = COALESCE(NULLIF(btrim(EXCLUDED.nome_fantasia), ''), wins_v2.entidades_lookup.nome_fantasia),                                                                                                                                                                                                                         +
         natureza_entidade = COALESCE(NULLIF(btrim(EXCLUDED.natureza_entidade), ''), wins_v2.entidades_lookup.natureza_entidade),                                                                                                                                                                                                             +
         municipio = COALESCE(NULLIF(btrim(EXCLUDED.municipio), ''), wins_v2.entidades_lookup.municipio),                                                                                                                                                                                                                                     +
         uf = COALESCE(EXCLUDED.uf, wins_v2.entidades_lookup.uf),                                                                                                                                                                                                                                                                             +
         fontes = CASE                                                                                                                                                                                                                                                                                                                        +
             WHEN wins_v2.entidades_lookup.fontes IS NULL OR wins_v2.entidades_lookup.fontes = '' THEN EXCLUDED.fontes                                                                                                                                                                                                                        +
             WHEN EXCLUDED.fontes IS NULL OR position(EXCLUDED.fontes in wins_v2.entidades_lookup.fontes) > 0                                                                                                                                                                                                                                 +
                 THEN wins_v2.entidades_lookup.fontes                                                                                                                                                                                                                                                                                         +
             ELSE wins_v2.entidades_lookup.fontes || '|' || EXCLUDED.fontes                                                                                                                                                                                                                                                                   +
         END,                                                                                                                                                                                                                                                                                                                                 +
         captadores = CASE                                                                                                                                                                                                                                                                                                                    +
             WHEN wins_v2.entidades_lookup.captadores IS NULL OR wins_v2.entidades_lookup.captadores = '' THEN EXCLUDED.captadores                                                                                                                                                                                                            +
             WHEN EXCLUDED.captadores IS NULL OR position(EXCLUDED.captadores in wins_v2.entidades_lookup.captadores) > 0                                                                                                                                                                                                                     +
                 THEN wins_v2.entidades_lookup.captadores                                                                                                                                                                                                                                                                                     +
             ELSE wins_v2.entidades_lookup.captadores || '|' || EXCLUDED.captadores                                                                                                                                                                                                                                                           +
         END,                                                                                                                                                                                                                                                                                                                                 +
         quantidade_ocorrencias = COALESCE(wins_v2.entidades_lookup.quantidade_ocorrencias, 0) + 1,                                                                                                                                                                                                                                           +
         importado_em = now()                                                                                                                                                                                                                                                                                                                 +
     RETURNING entidade_id INTO v_id;                                                                                                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                                                                              +
     RETURN v_id;                                                                                                                                                                                                                                                                                                                             +
 END;                                                                                                                                                                                                                                                                                                                                         +
 $function$                                                                                                                                                                                                                                                                                                                                   +
 

